In [1]:
import os
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [2]:
def load_data(file_name):
    data = pd.read_csv(file_name)
    if 'WLoc' in data.columns:
        data.loc[data['WLoc'] == 'N', 'WLoc'] = 0
        data.loc[data['WLoc'] == 'H', 'WLoc'] = 1
        data.loc[data['WLoc'] == 'A', 'WLoc'] = -1
    return data

In [3]:
data_path = os.path.join("..", "data", "march-machine-learning-mania-2023")
reg = load_data(os.path.join(data_path, "MRegularSeasonDetailedResults.csv"))
for (i,c) in enumerate(reg.columns):
    if i > 0 and i % 8 == 0:
        print()
    print(f'{c:10}', end='')

Season    DayNum    WTeamID   WScore    LTeamID   LScore    WLoc      NumOT     
WFGM      WFGA      WFGM3     WFGA3     WFTM      WFTA      WOR       WDR       
WAst      WTO       WStl      WBlk      WPF       LFGM      LFGA      LFGM3     
LFGA3     LFTM      LFTA      LOR       LDR       LAst      LTO       LStl      
LBlk      LPF       

In [5]:
fields = ['WScore', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'LScore', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3', 'WLoc']
reg[fields]

WScore  WFGM  WFGA  WFGM3  WFGA3  LScore  LFGM  LFGA  LFGM3  LFGA3  \
0           68    27    58      3     14      62    22    53      2     10   
1           70    26    62      8     20      63    24    67      6     24   
2           73    24    58      8     18      61    22    73      3     26   
3           56    18    38      3      9      50    18    49      6     22   
4           77    30    61      6     14      71    24    62      6     16   
...        ...   ...   ...    ...    ...     ...   ...   ...    ...    ...   
106829      74    29    47      7     12      63    21    59      9     33   
106830      84    32    61     10     20      63    26    59      4     21   
106831      65    21    51      7     27      55    17    54      6     23   
106832      88    31    59     11     19      63    21    56      8     28   
106833      64    25    56      6     19      63    23    51      8     23   

       WLoc  
0         0  
1         0  
2         0  
3         0  
4         0  
...     ...  
106829   -1  
106830    1  
106831   -1  
106832   -1  
106833   -1  

[106834 rows x 11 columns]

In [6]:
arr = reg[fields].to_numpy()
scaler = StandardScaler()
scaler.fit(arr)

StandardScaler()

In [11]:
scaled_arr = scaler.transform(arr)
scaled_arr

array([[-0.688976  ,  0.15453822,  0.32799713, ..., -1.4858242 ,
        -1.64970941, -0.31037159],
       [-0.50745629, -0.05912732,  0.86228462, ..., -0.05523684,
         0.67172409, -0.31037159],
       [-0.23517672, -0.48645841,  0.32799713, ..., -1.12817736,
         1.00335744, -0.31037159],
       ...,
       [-0.96125557, -1.12745504, -0.60700599, ..., -0.05523684,
         0.50590741, -1.41454205],
       [ 1.12622112,  1.0092004 ,  0.461569  , ...,  0.66005684,
         1.3349908 , -1.41454205],
       [-1.05201542, -0.27279286,  0.06085338, ...,  0.66005684,
         0.50590741, -1.41454205]])

In [12]:
pca = PCA(n_components=3, random_state=2023)
pca.fit(scaled_arr)
pca.transform(scaled_arr)

array([[-1.66479316,  0.32424517,  2.21422798],
       [ 0.75216083, -0.30251446, -0.22116454],
       [ 0.27441981, -0.4265178 ,  0.04168778],
       ...,
       [-1.56569655,  0.33313559, -1.85181607],
       [ 1.51011445,  0.13821226, -1.04017073],
       [-0.59119755, -0.77214077, -0.79048476]])

In [14]:
pca.explained_variance_

array([4.18475997, 1.72999143, 1.28835578])

In [15]:
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'